"""
m8tes - Python SDK for m8tes.ai

Developer SDK for building autonomous agents.
"""

from importlib.metadata import PackageNotFoundError, version

try:
    __version__ = version("m8tes")
except PackageNotFoundError:
    __version__ = "0.0.0-dev"

# ── v2 Developer SDK (primary) ───────────────────────────────────────
from ._auth import get_token, signup, signup_and_wait
from ._client import M8tes
from ._exceptions import (
    APIError,
    AuthenticationError,
    BillingError,
    ConflictError,
    M8tesError,
    NotFoundError,
    PermissionDeniedError,
    RateLimitError,
    RunFailedError,
    ValidationError,
)
from ._resources.auth import Auth
from ._resources.billing import Billing
from ._resources.channels import Channels
from ._resources.webhooks import Webhooks
from ._streaming import RunStream
from ._types import (
    AccountSettings,
    Agent,
    AgentSystemPrompt,
    AgentTemplate,
    ApiKeyCreated,
    ApiKeyInfo,
    ApiKeyRotated,
    App,
    AppConnection,
    AppConnectionInitiation,
    AppConnectionResult,
    ApplyPreferredModelResult,
    AppProvisionResult,
    AppTool,
    AppTriggerType,
    AuditLog,
    Balance,
    Bridge,
    BuiltInTool,
    Channel,
    ChannelInstallLinks,
    EmailInbox,
    EndUser,
    EndUserUsage,
    GitHubInstallLink,
    HandleLink,
    Lesson,
    LessonList,
    McpServer,
    Memory,
    Model,
    ModelAuthorization,
    ModelConnection,
    ModelPricing,
    NamedApiKey,
    PermissionMode,
    PermissionModeResponse,
    PermissionPolicy,
    PermissionRequest,
    Plan,
    Receipt,
    Run,
    RunCheck,
    RunFile,
    RunMessage,
    RunOutcome,
    RunShare,
    RunUsage,
    SignupResult,
    Skill,
    SlackInstallLink,
    SyncPage,
    Task,
    Teammate,
    TeammateDocument,
    TeammateTemplate,
    TeammateWebhook,
    TokenResult,
    TokenTransaction,
    Trigger,
    Usage,
    UsageBucket,
    UsageModelSlice,
    UsageTimeseries,
    UsageTotals,
    Webhook,
    WebhookDelivery,
)

# ── CLI/session exports ──────────────────────────────────────────────
from .exceptions import (
    AgentError,
    DeploymentError,
    IntegrationError,
    NetworkError,
    OAuthError,
    TimeoutError,
)
from .streaming import (
    DoneEvent,
    ErrorEvent,
    MetricsEvent,
    StreamEvent,
    StreamEventType,
    TextDeltaEvent,
    ToolCallDeltaEvent,
    ToolCallStartEvent,
    ToolResultEndEvent,
)

__all__ = [
    "APIError",
    "AccountSettings",
    "Agent",
    "AgentError",
    "AgentSystemPrompt",
    "AgentTemplate",
    "ApiKeyCreated",
    "ApiKeyInfo",
    "ApiKeyRotated",
    "App",
    "AppConnection",
    "AppConnectionInitiation",
    "AppConnectionResult",
    "AppProvisionResult",
    "AppTool",
    "AppTriggerType",
    "ApplyPreferredModelResult",
    "AuditLog",
    "Auth",
    "AuthenticationError",
    "Balance",
    "Billing",
    "BillingError",
    "Bridge",
    "BuiltInTool",
    "Channel",
    "ChannelInstallLinks",
    "Channels",
    "ConflictError",
    "DeploymentError",
    "DoneEvent",
    "EmailInbox",
    "EndUser",
    "EndUserUsage",
    "ErrorEvent",
    "GitHubInstallLink",
    "HandleLink",
    "IntegrationError",
    "Lesson",
    "LessonList",
    "M8tes",
    "M8tesError",
    "McpServer",
    "Memory",
    "MetricsEvent",
    "Model",
    "ModelAuthorization",
    "ModelConnection",
    "ModelPricing",
    "NamedApiKey",
    "NetworkError",
    "NotFoundError",
    "OAuthError",
    "PermissionDeniedError",
    "PermissionMode",
    "PermissionModeResponse",
    "PermissionPolicy",
    "PermissionRequest",
    "Plan",
    "RateLimitError",
    "Receipt",
    "Run",
    "RunCheck",
    "RunFailedError",
    "RunFile",
    "RunMessage",
    "RunOutcome",
    "RunShare",
    "RunStream",
    "RunUsage",
    "SignupResult",
    "Skill",
    "SlackInstallLink",
    "StreamEvent",
    "StreamEventType",
    "SyncPage",
    "Task",
    "Teammate",
    "TeammateDocument",
    "TeammateTemplate",
    "TeammateWebhook",
    "TextDeltaEvent",
    "TimeoutError",
    "TokenResult",
    "TokenTransaction",
    "ToolCallDeltaEvent",
    "ToolCallStartEvent",
    "ToolResultEndEvent",
    "Trigger",
    "Usage",
    "UsageBucket",
    "UsageModelSlice",
    "UsageTimeseries",
    "UsageTotals",
    "ValidationError",
    "Webhook",
    "WebhookDelivery",
    "Webhooks",
    "get_token",
    "signup",
    "signup_and_wait",
]
